-- Nuez Co POS: un mismo producto puede estar repartido en varias cajas (del local o del depósito),
-- con la cantidad anotada en cada una. Pegalo UNA vez en Supabase > SQL Editor > Run.
-- No modifica ni borra datos. Es seguro repetirlo.
-- El stock total sigue siendo el de siempre; esto solo anota DÓNDE está (y cuánto, como referencia).

do $$
declare tipo text;
begin
  select format_type(a.atttypid, a.atttypmod) into tipo
    from pg_attribute a
   where a.attrelid = 'public.productos'::regclass and a.attname = 'id';
  execute format(
    'create table if not exists public.stock_cajas (
       id bigint generated by default as identity primary key,
       producto_id %s not null references public.productos(id) on delete cascade,
       zona text not null check (zona in (''local'', ''deposito'')),
       caja text not null,
       cantidad numeric,
       creado_en timestamptz not null default now(),
       unique (producto_id, zona, caja)
     )', tipo);
end $$;

alter table public.stock_cajas enable row level security;
drop policy if exists "stock_cajas_admin" on public.stock_cajas;
create policy "stock_cajas_admin" on public.stock_cajas for all to authenticated using (true) with check (true);
grant select, insert, update, delete on public.stock_cajas to authenticated;

-- Las ubicaciones que ya tenías cargadas (una por producto) pasan solas a la tabla nueva, sin cantidad.
do $$
begin
  insert into public.stock_cajas (producto_id, zona, caja)
  select s.producto_id,
         case when u.nombre = 'Local' then 'local' else 'deposito' end,
         s.ubicacion_detalle
    from public.stock s
    join public.ubicaciones u on u.id = s.ubicacion_id
   where s.ubicacion_detalle is not null and btrim(s.ubicacion_detalle) <> ''
     and u.nombre in ('Local', 'Depósito')
  on conflict (producto_id, zona, caja) do nothing;
end $$;

notify pgrst, 'reload schema';
